### ISSUE TITLE
Battery Cost

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-Sienna/PowerSystems.jl#934] opened 2022-12-07 18:41 UTC

**Comment by claytonpbarrows** [comment] 2023-01-09 20:58
add battery EMS cost validation exceptions

**Comment by sourabhdalvi** [comment] 2023-04-18 22:42
I can't reproduce the validation message, I'm assuming this is fixed

**Comment by jd-lara** [comment] 2024-03-08 17:44
duplicate of #720

**Closed by jd-lara** 2024-03-08 17:44 UTC
Labels: New Version 4.0
